services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ness150703**
      MYSQL_DATABASE: crm_lca
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pness150703**"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: crm_lca
      DB_USER: root
      DB_PASSWORD: ness150703**
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data: