# Generated by Django 6.0.7 on 2026-07-13 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Social', 'Social')], max_length=20)),
                ('status', models.CharField(choices=[('Planifiée', 'Planifiée'), ('Active', 'Active'), ('Terminée', 'Terminée')], default='Planifiée', max_length=20)),
                ('sent_count', models.IntegerField(default=0)),
                ('opens_count', models.IntegerField(default=0)),
                ('conversions_count', models.IntegerField(default=0)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('activity_domain', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('acquisition_channel', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Lead', 'Lead'), ('Client', 'Client'), ('Partenaire', 'Partenaire')], default='Lead', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Email', 'Email'), ('Appel', 'Appel'), ('Réunion', 'Réunion'), ('Entretien', 'Entretien'), ('Visite', 'Visite sur site')], max_length=20)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(blank=True, max_length=30)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('project_subject', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(choices=[('Qualification', 'Qualification'), ('Chiffrage', 'Chiffrage / Analyse (Rédaction)'), ('Offre Soumise', 'Offre Soumise (Attente)'), ('Négociation', 'Négociation (Ajustement)'), ('Clôturé', 'Clôturé (Fin de cycle)')], default='Qualification', max_length=30)),
                ('result', models.CharField(choices=[('En cours', 'En cours'), ('Gagné', 'Gagné'), ('Perdu', 'Perdu')], default='En cours', max_length=20)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('probability', models.IntegerField(default=0)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('lost_reason', models.TextField(blank=True)),
                ('action_plan', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.company')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Ouverte', 'Ouverte'), ('En cours', 'En cours'), ('Résolue', 'Résolue')], default='Ouverte', max_length=20)),
                ('priority', models.CharField(choices=[('Faible', 'Faible'), ('Moyenne', 'Moyenne'), ('Élevée', 'Élevée')], default='Moyenne', max_length=20)),
                ('channel', models.CharField(choices=[('Téléphone', 'Téléphone'), ('Email', 'Email'), ('Réunion', 'Réunion'), ('Formulaire web', 'Formulaire web'), ('Portail client', 'Portail client')], default='Téléphone', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField()),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.reclamation')),
            ],
        ),
    ]
