# Generated by Django 6.0.7 on 2026-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('probleme', models.TextField()),
                ('origine', models.CharField(blank=True, max_length=150)),
                ('processus', models.CharField(choices=[('PMS', 'Pilotage et Management Stratégique'), ('PCS', 'Prestation de Consulting'), ('PRT', 'Prestation de Recrutement'), ('PFR', 'Prestation de Formation'), ('GFS', 'Gestion des Fonctions Support')], max_length=10)),
                ('gravite', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Élevée / Majeure')])),
                ('action_immediate', models.TextField(blank=True)),
                ('analyse_causes', models.TextField(blank=True)),
                ('recurrence', models.BooleanField(default=False)),
                ('action_corrective', models.TextField(blank=True)),
                ('date_prevue', models.CharField(blank=True, max_length=50)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('date_realisation', models.CharField(blank=True, max_length=50)),
                ('delais', models.CharField(blank=True, max_length=100)),
                ('efficacite', models.CharField(blank=True, choices=[('Efficace', 'Efficace'), ('Non efficace', 'Non efficace'), ('Insuffisant', 'Insuffisant'), ('A vérifier', 'À vérifier')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('avancement', models.CharField(choices=[('P', 'Planifier'), ('D', 'Réaliser'), ('C', 'Contrôler'), ('A', 'Acter (clôturer)')], default='P', max_length=1)),
                ('statut', models.CharField(choices=[('Ouvert', 'Ouvert'), ('Clos', 'Clos')], default='Ouvert', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
    ]
