# Generated by Django 6.0.7 on 2026-07-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_nonconformite'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='service_provided',
            field=models.CharField(blank=True, choices=[('Recrutement', 'Recrutement'), ('Formation', 'Formation'), ('Consulting', 'Consulting')], max_length=50),
        ),
    ]
