# Generated by Django 6.0.7 on 2026-07-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_company_service_provided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformite',
            name='statut',
            field=models.CharField(choices=[('Ouvert', 'Ouvert'), ('Fermé', 'Fermé')], default='Ouvert', max_length=10),
        ),
    ]
