# Generated by Django 6.0.7 on 2026-07-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_nonconformite_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='plan_action',
            field=models.TextField(blank=True),
        ),
    ]
