# Generated by Django 6.0.7 on 2026-07-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_satisfactionsurveypdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satisfactionsurveypdf',
            options={'ordering': ['-year', '-uploaded_at']},
        ),
        migrations.AlterUniqueTogether(
            name='satisfactionsurveypdf',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='satisfactionsurveypdf',
            name='amelioration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='satisfactionsurveypdf',
            name='future_intent',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non'), ('Peut-être', 'Peut-être')], default='Oui', max_length=15),
        ),
        migrations.AddField(
            model_name='satisfactionsurveypdf',
            name='point_fort',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='satisfactionsurveypdf',
            name='score_global',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='satisfactionsurveypdf',
            name='score_recommendation',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='satisfactionsurveypdf',
            name='service_type',
            field=models.CharField(choices=[('Consulting', 'Consulting'), ('Formation', 'Formation'), ('Recrutement', 'Recrutement')], default='Consulting', max_length=20),
        ),
        migrations.AlterField(
            model_name='satisfactionsurveypdf',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='satisfaction_pdfs/%Y/'),
        ),
    ]
