# Generated by Django 6.0.7 on 2026-07-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_satisfactionsurveypdf_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionsurveypdf',
            name='detailed_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
