# Generated by Django 6.0.7 on 2026-08-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_satisfactionsurveypdf_detailed_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='convention_contrat',
            field=models.CharField(blank=True, default='Non', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='cv_document',
            field=models.FileField(blank=True, null=True, upload_to='prestataire_cvs/%Y/'),
        ),
        migrations.AddField(
            model_name='company',
            name='date_debut_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='date_fin_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fonction_interlocuteur',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='interlocuteur_principal',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='patente',
            field=models.CharField(blank=True, default='Oui', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='service_provided',
            field=models.CharField(blank=True, choices=[('Recrutement', 'Recrutement'), ('Formation', 'Formation'), ('Consulting', 'Consulting'), ('Comptable', 'Comptable'), ('Fourniture bureautique', 'Fourniture bureautique'), ('Informatique', 'Informatique'), ('Autre', 'Autre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Client', 'Client'), ('Partenaire', 'Partenaire'), ('Prestataire', 'Prestataire')], default='Lead', max_length=20),
        ),
        migrations.CreateModel(
            name='PrestataireEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('prix', models.FloatField(blank=True, null=True)),
                ('qualite', models.FloatField(blank=True, null=True)),
                ('prestation_service', models.FloatField(blank=True, null=True)),
                ('respect_delais', models.FloatField(blank=True, null=True)),
                ('score_percent', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_evaluations', to='crm.company')),
            ],
            options={
                'ordering': ['-year', 'company__name'],
                'unique_together': {('company', 'year')},
            },
        ),
    ]
