# Generated by Django 6.0.7 on 2026-08-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_add_email_phone_to_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestataire',
            fields=[
            ],
            options={
                'verbose_name': 'Prestataire',
                'verbose_name_plural': 'Prestataires',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.company',),
        ),
    ]
