# Generated by Django 6.0.7 on 2026-08-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_add_prestataire_proxy_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamationnote',
            name='reclamation',
        ),
        migrations.DeleteModel(
            name='Reclamation',
        ),
        migrations.DeleteModel(
            name='ReclamationNote',
        ),
    ]
