# Generated by Django 6.0.7 on 2026-08-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_reclamationnote_reclamation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='collaboration_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='is_retained',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='service_provided',
            field=models.CharField(blank=True, choices=[('Recrutement', 'Recrutement'), ('Formation', 'Formation'), ('Consulting', 'Consulting'), ('Comptable', 'Comptable'), ('Fourniture', 'Fourniture'), ('Fourniture bureautique', 'Fourniture bureautique'), ('Informatique', 'Informatique'), ('Autre', 'Autre')], max_length=100),
        ),
    ]
